cp -r output/alpha_0/* saveOutput/FiveParams/alpha_0/.
cp -r output/alpha_1/* saveOutput/FiveParams/alpha_1/.
cp -r output/alpha_2/* saveOutput/FiveParams/alpha_2/.
cp -r output/alpha_3/* saveOutput/FiveParams/alpha_3/.
cp -r output/alpha_4/* saveOutput/FiveParams/alpha_4/.
cp -r output/alpha_5/* saveOutput/FiveParams/alpha_5/.
cp -r output/alpha_6/* saveOutput/FiveParams/alpha_6/.
cp -r output/alpha_7/* saveOutput/FiveParams/alpha_7/.
cp -r output/alpha_8/* saveOutput/FiveParams/alpha_8/.
cp -r output/alpha_9/* saveOutput/FiveParams/alpha_9/.
cp -r output/alpha_10/* saveOutput/FiveParams/alpha_10/.
cp -r output/alpha_11/* saveOutput/FiveParams/alpha_11/.
cp -r output/alpha_12/* saveOutput/FiveParams/alpha_12/.
cp -r output/alpha_13/* saveOutput/FiveParams/alpha_13/.
cp -r output/alpha_14/* saveOutput/FiveParams/alpha_14/.
